# Generated by Django 6.0.3 on 2026-03-16 00:00

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^255\\d{9}$",
                        message="Phone number must be in the format 255XXXXXXXXX.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hardwarestore",
            name="delivery_capacity_units_per_day",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_units",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_eta_hours",
            field=models.IntegerField(
                default=24, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity_units",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^255\\d{9}$",
                        message="Phone number must be in the format 255XXXXXXXXX.",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["role"], name="core_profil_role_idx"),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["area"], name="core_profil_area_idx"),
        ),
        migrations.AddIndex(
            model_name="hardwarestore",
            index=models.Index(
                fields=["active", "area"], name="core_hardw_active_area_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hardwarestore",
            index=models.Index(
                fields=["owner", "active"], name="core_hardw_owner_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["active", "category"], name="core_produ_active_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["store", "active"], name="core_produ_store_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "payment_status"],
                name="core_order_status_payment_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store", "created_at"],
                name="core_order_store_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["fundi", "created_at"],
                name="core_order_fundi_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="core_orderi_order_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product"], name="core_orderi_product_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "method"], name="core_payme_status_method_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="core_notif_user_read_idx"
            ),
        ),
    ]
