# Generated by Django 6.0.3 on 2026-03-16 00:00

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^255\\d{9}$",
                        message="Phone number must be in the format 255XXXXXXXXX.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="hardwarestore",
            name="delivery_capacity_units_per_day",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_units",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_eta_hours",
            field=models.IntegerField(
                default=24, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity_units",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^255\\d{9}$",
                        message="Phone number must be in the format 255XXXXXXXXX.",
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["role"]),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["area"]),
        ),
        migrations.AddIndex(
            model_name="hardwarestore",
            index=models.Index(
                fields=["active", "area"]
            ),
        ),
        migrations.AddIndex(
            model_name="hardwarestore",
            index=models.Index(
                fields=["owner", "active"]
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["active", "category"]
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["store", "active"]
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "payment_status"],
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["store", "created_at"],
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["fundi", "created_at"],
            ),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"]),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(
                fields=["product"]
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "method"]
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"]
            ),
        ),
    ]
